/**
 * Game data for Play Together (PTG / 661)
 * Period: Aug 2025 – Jan 2026 (6 months, 184 days)
 * Source: generated-data.ts (generated by scripts/generate-data.js)
 * 
 * Re-exports types and data from generated-data.ts.
 * All helper functions filter the unified 6-month dataset.
 */

import {
  DAILY_USERS,
  DAILY_REVENUE,
  MONTHLY_SUMMARIES,
  DATA_RANGE,
} from './generated-data';
import type { DailyUserRecord, DailyRevenueRecord, MonthlySummary } from './generated-data';

// Re-export for backwards compatibility
export type { DailyUserRecord, DailyRevenueRecord, MonthlySummary };
export { DAILY_USERS, DAILY_REVENUE, MONTHLY_SUMMARIES, DATA_RANGE };

// ── Date formatting helper ────────────────────────────────────
const fmtDate = (d: string) => {
  const dt = new Date(d);
  return (dt.getMonth() + 1) + '/' + dt.getDate();
};

// ── Get the previous month string (YYYY-MM) ───────────────────
function prevMonth(yearMonth: string): string {
  const [y, m] = yearMonth.split('-').map(Number);
  const pm = m === 1 ? 12 : m - 1;
  const py = m === 1 ? y - 1 : y;
  return `${py}-${String(pm).padStart(2, '0')}`;
}

// ── Resolve data array by source string ───────────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function resolveData(source: string): any[] {
  return source.includes('REVENUE') ? DAILY_REVENUE : DAILY_USERS;
}

// ── getMetricData: get last N days from the end of dataset ────
export function getMetricData(
  field: string,
  source: string,
  timeRange: 'last_7_days' | 'last_14_days' | 'last_30_days' = 'last_30_days'
): { labels: string[]; values: number[] } {
  const data = resolveData(source);
  const sliceN =
    timeRange === 'last_7_days' ? 7 : timeRange === 'last_14_days' ? 14 : 30;
  const sliced = data.slice(-sliceN);

  return {
    labels: sliced.map((r) => fmtDate(r.date as string)),
    values: sliced.map((r) => +(r[field] as number) || 0),
  };
}

// ── getPrevMetricData: get previous month's matching N days ───
export function getPrevMetricData(
  field: string,
  source: string,
  timeRange: 'last_7_days' | 'last_14_days' | 'last_30_days' = 'last_30_days'
): { labels: string[]; values: number[] } | null {
  const data = resolveData(source);

  // Check if field exists in the data
  if (data.length === 0 || !(field in data[0])) return null;

  // Get the latest month in the dataset, then find the previous month
  const lastDate = (data[data.length - 1].date as string);
  const lastYM = lastDate.slice(0, 7);
  const prevYM = prevMonth(lastYM);

  // Filter to previous month
  const prevData = data.filter((r) => (r.date as string).startsWith(prevYM));
  if (prevData.length === 0) return null;

  const sliceN =
    timeRange === 'last_7_days' ? 7 : timeRange === 'last_14_days' ? 14 : 30;
  const sliced = prevData.slice(-sliceN);

  return {
    labels: sliced.map((r) => fmtDate(r.date as string)),
    values: sliced.map((r) => +(r[field] as number) || 0),
  };
}

// ── getMetricDataByDateRange: filter by arbitrary date range ──
export function getMetricDataByDateRange(
  field: string,
  source: string,
  startDate: string,
  endDate: string
): { labels: string[]; values: number[] } {
  const data = resolveData(source);
  const filtered = data.filter((r) => (r.date as string) >= startDate && (r.date as string) <= endDate);
  return {
    labels: filtered.map((r) => fmtDate(r.date as string)),
    values: filtered.map((r) => +(r[field] as number) || 0),
  };
}
